version: '3'

networks:
    nginx-php8-mysql8-node:


services:

    nginx-services:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./html:/var/www/public
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php8-service
        networks:
            - nginx-php8-mysql8-node

    php8-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php8-container
        ports: 
            - "9000:9000"
        #volumes: 
        #    - ./app:/var/www/project
        networks:
            - nginx-php8-mysql8-node


    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks: 
            - nginx-php8-mysql8-node
            